import { GoogleGenAI } from "@google/genai";
import { Orientation } from "../types";

const getAspectRatio = (orientation: Orientation): "1:1" | "4:3" | "3:4" => {
    switch (orientation) {
        case 'Landscape': return '4:3';
        case 'Portrait': return '3:4';
        case 'Square': return '1:1';
        default: return '1:1';
    }
};

export const generateImage = async (prompt: string, orientation: Orientation): Promise<string> => {
    // FIX: Aligned with API guidelines by removing API key check and fallback logic.
    // The API key is expected to be available in the environment.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: getAspectRatio(orientation),
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image with Gemini API:", error);
        throw new Error("Failed to communicate with the image generation service.");
    }
};
